spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit_order?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    port: 5672
    host: 119.23.241.183
    virtual-host: /
    username: admin
    password: admin
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

